// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApOCVtbwp6gdqqyrheDy298yqma-RpbE0',
    appId: '1:561879108691:android:9270712cdb1e3054950aa6',
    messagingSenderId: '561879108691',
    projectId: 'mycustomnotes',
    storageBucket: 'mycustomnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKV68HzlAQ_n5oqrKUzYyS0sUMc3J5VZU',
    appId: '1:561879108691:ios:f1ab19660956dcef950aa6',
    messagingSenderId: '561879108691',
    projectId: 'mycustomnotes',
    storageBucket: 'mycustomnotes.appspot.com',
    androidClientId: '561879108691-2cr6635v93524ubc3o8j1qgrnetb86ic.apps.googleusercontent.com',
    iosClientId: '561879108691-60um329gqvmgbiftd6m8pfcv3rchq5u0.apps.googleusercontent.com',
    iosBundleId: 'com.nicolasferrada.mycustomnotes',
  );
}
